version: 2

updates:
  - package-ecosystem: github-actions

    directory: /

    schedule:
      # run weekly on mondays at 00:00 utc
      interval: weekly
      day: monday
      time: "00:00"

    groups:
      github-actions:
        patterns:
          - "*"

    assignees:
      - hilorioze

    labels:
      - dependencies
      - github_actions
      - automated

    commit-message:
      prefix: chore(deps/github-actions)

  - package-ecosystem: nix

    directory: /

    schedule:
      # run weekly on mondays at 00:00 utc
      interval: weekly
      day: monday
      time: "00:00"

    groups:
      nix:
        patterns:
          - "*"

    assignees:
      - hilorioze

    labels:
      - dependencies
      - nix
      - flake
      - automated

    commit-message:
      prefix: chore(deps/nix)
